# Generated by Django 4.0.3 on 2022-04-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_katilimci_soy_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='katilimci',
            name='etkinlik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Etkinlik'),
            preserve_default=False,
        ),
    ]
