# Generated by Django 4.0.3 on 2022-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_katilimci_etkinlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katilimci',
            name='etkinlik',
            field=models.CharField(max_length=50, verbose_name='Etkinlik'),
        ),
    ]
