# Generated by Django 4.0.3 on 2022-04-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_katilimci_etkinlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
