# Generated by Django 4.0.3 on 2022-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katilimci',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='etkinlik',
            field=models.CharField(blank=True, max_length=50, verbose_name='Etkinlik'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='isim',
            field=models.CharField(max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='soy_isim',
            field=models.CharField(max_length=50, verbose_name='Soy İsim'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='tc_no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='TC Kimlik No'),
        ),
    ]
