# Generated by Django 4.0.3 on 2022-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_katilimci_email_alter_katilimci_etkinlik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katilimci',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='etkinlik',
            field=models.CharField(blank=True, max_length=250, verbose_name='Etkinlik'),
        ),
    ]
