# Generated by Django 4.0.3 on 2022-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_katilimci_email_alter_katilimci_etkinlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikalar',
            fields=[
                ('etkinlik_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Etkinlik ID')),
                ('sertifika', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sertifika')),
                ('kordinat_isim', models.CharField(max_length=50, verbose_name='Kordinat İsim')),
                ('kordinat_tarih', models.CharField(max_length=50, verbose_name='Kordinat Tarih')),
                ('kordinat_qr', models.CharField(max_length=50, verbose_name='Kordinat QR')),
                ('ornek_sertifika', models.FileField(blank=True, null=True, upload_to='', verbose_name='Örnek Sertifika')),
            ],
        ),
    ]
