# Generated by Django 4.0.3 on 2022-05-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_veritabanisertifikalar_sertifika_etkinlik_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='veritabanisertifikalar',
            name='katilimci_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
