# Generated by Django 4.0.3 on 2022-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_veritabanisertifikalar_katilimci_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='veritabanisertifikalar',
            name='katilimci_tc',
            field=models.IntegerField(blank=True, null=True, verbose_name='TC Kimlik No'),
        ),
    ]
