# Generated by Django 4.0.3 on 2022-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_veritabanisertifikalar_katilimci_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='veritabanisertifikalar',
            name='sertifika_mevcut',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
