# Generated by Django 4.0.3 on 2022-05-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_veritabanisertifikalar_ad_soyad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Etkinlik', 'verbose_name_plural': 'Etkinlikler'},
        ),
    ]
